# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4519d9e29e3e63e717ad8011874a04c745b2b8769d6f71d451cbd0eab3988af2d63f2dc38f08950db435d45862027da7cbf57697c43f6ffcb0c4b8fbe99e5383

test:
  secret_key_base: 81c2f848e96550af5732aa128bc0cff1d1644b0e17704d116687c6c52064e5af4b5503d8547d42795135793f5cd77fe321174a9c4bd6f58dce6510ca194466c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
